In [1]:
#Step 1 : Import the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Import Dataset
dataset=pd.read_csv('Housing_Data.csv')

In [3]:
dataset

Income  House Age  Area Number of Rooms  Area Number of Bedrooms  \
0     79545.45857   5.682861              7.009188                     4.09   
1     79248.64245   6.002900              6.730821                     3.09   
2     61287.06718   5.865890              8.512727                     5.13   
3     63345.24005   7.188236              5.586729                     3.26   
4     59982.19723   5.040555              7.839388                     4.23   
...           ...        ...                   ...                      ...   
4995  60567.94414   7.830362              6.137356                     3.46   
4996  78491.27543   6.999135              6.576763                     4.02   
4997  63390.68689   7.250591              4.805081                     2.13   
4998  68001.33124   5.534388              7.130144                     5.44   
4999  65510.58180   5.992305              6.792336                     4.07   

      Area Population         Price  
0         23086.80050  1.059034e+06  
1         40173.07217  1.505891e+06  
2         36882.15940  1.058988e+06  
3         34310.24283  1.260617e+06  
4         26354.10947  6.309435e+05  
...               ...           ...  
4995      22837.36103  1.060194e+06  
4996      25616.11549  1.482618e+06  
4997      33266.14549  1.030730e+06  
4998      42625.62016  1.198657e+06  
4999      46501.28380  1.298950e+06  

[5000 rows x 6 columns]

In [4]:
#Step 3: Divide Feature Matrix(X) and Dependable Variable Vector(Y)
X=dataset.iloc[:,:-1].values  
Y=dataset.iloc[:,-1].values

In [5]:
#Step 4: Replace the missing data
from  sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,:]) 
X[:,:]=imputer.transform(X[:,:])

In [6]:
#step 6: Splitting data
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.2,random_state=1)

# Building multiple linear regression model

In [7]:
#Step1:training the linear model
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(Xtrain,Ytrain)

LinearRegression()

In [8]:
#Step2: Testing the Linear Model
Yestimated=LR.predict(Xtest)
print(Yestimated)

[1554219.15762203 1582983.38785291  941849.34310379  943752.69950732
 1183410.51031803  330129.92093545 1927632.21189598 1069922.75406543
 1648778.05618107 1073503.34522901  626617.7040675  1538963.80618587
 1631224.37750971 1054158.78454091  961171.82965125 1234681.84681193
 1428653.88192771  925913.80226774 1128251.49775708 1159562.12635962
 1296553.35384095 1865297.38766109 1183231.4091539  1190862.36427286
 1557482.81715817 1862543.13058049  814308.00880997 1063737.59178209
 1226259.21081068  661221.03377593  843011.58134936 1636180.75120876
  665986.95406143 1117105.96878451  800237.32655294 1304234.70596083
 1147460.64721372 1349717.5101874  1034432.05415932 1162747.68744767
 1413050.18421862 1309555.41911969 1576626.16951888 1300214.75688119
  848763.75142763  924167.81958801 1229362.35989918 1161822.48798862
 1422081.71554106 1334121.39586392 1571121.62994741  747837.45566804
  756756.12377097 1036926.2498654  1232318.03872197 1310197.28867452
 1542384.48553879 1074886.84081346

In [9]:
print(Ytest)

[1413579.817   1618721.138    841392.493    881443.9247  1174747.551
  266298.8811  1877941.971   1022408.901   1766248.403    949072.2496
  565937.2006  1437153.959   1582605.535   1009854.705   1116351.753
 1255736.409   1504441.01     837540.1697  1096069.287   1205962.995
 1130844.029   1815920.45    1023595.113   1054304.172   1399909.049
 1710612.03     670063.0223  1245785.051   1168760.428    412269.2034
  677988.2555  1715435.991    662630.3439  1167449.99     714706.4289
 1411217.493   1200125.447   1322439.108   1127637.557   1066040.789
 1383842.185   1364306.769   1682105.847   1380602.556    880084.7004
  779207.5546  1029861.623   1106149.686   1327806.729   1377939.775
 1584317.753    944288.911    759799.8758  1028493.601   1164497.019
 1383508.062   1696339.544    930011.5709  1092649.709   1686562.169
 1376969.929    868314.4736  1660678.035   1533017.307   1735340.256
 1735416.921   1771036.925   1068786.672    731715.2643   934610.3953
 1137069.307   1088634.962   

In [12]:
Yestimated.reshape(len(Yestimated),1)
Ytest.reshape(len(Ytest),1)

array([[1413579.817  ],
       [1618721.138  ],
       [ 841392.493  ],
       [ 881443.9247 ],
       [1174747.551  ],
       [ 266298.8811 ],
       [1877941.971  ],
       [1022408.901  ],
       [1766248.403  ],
       [ 949072.2496 ],
       [ 565937.2006 ],
       [1437153.959  ],
       [1582605.535  ],
       [1009854.705  ],
       [1116351.753  ],
       [1255736.409  ],
       [1504441.01   ],
       [ 837540.1697 ],
       [1096069.287  ],
       [1205962.995  ],
       [1130844.029  ],
       [1815920.45   ],
       [1023595.113  ],
       [1054304.172  ],
       [1399909.049  ],
       [1710612.03   ],
       [ 670063.0223 ],
       [1245785.051  ],
       [1168760.428  ],
       [ 412269.2034 ],
       [ 677988.2555 ],
       [1715435.991  ],
       [ 662630.3439 ],
       [1167449.99   ],
       [ 714706.4289 ],
       [1411217.493  ],
       [1200125.447  ],
       [1322439.108  ],
       [1127637.557  ],
       [1066040.789  ],
       [1383842.185  ],
       [1364306.

In [14]:
np.concatenate((Yestimated.reshape(len(Yestimated),1),Ytest.reshape(len(Ytest),1)),1)

array([[1554219.15762203, 1413579.817     ],
       [1582983.38785291, 1618721.138     ],
       [ 941849.34310379,  841392.493     ],
       ...,
       [1717971.5809346 , 1644923.078     ],
       [1007962.88533644, 1106336.838     ],
       [ 829010.93814413,  759044.688     ]])

In [15]:
#Coefficients of the regression
LR.coef_

array([2.16667346e+01, 1.64990052e+05, 1.20784238e+05, 1.54252467e+03,
       1.51503697e+01])

In [16]:
LR.intercept_

-2637185.640093589

# Project 1:
## Prepare a preprocessing dataset
## Build a multilinear regression model using data obtained in preprocessing,find linear coeff and intercept of the model
## Using the model, determine in 2nd part, find the net turnover for the following row vector.
   #### CI=50661
   #### ES=115641
   #### Adv = 92496
   #### City=Bangalore