In [2]:
#Step 1 : Import the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

ModuleNotFoundError: No module named 'matplotlib'

In [2]:
#Step 2: Import data
dataset=pd.read_csv('Logistic Data.csv')

In [3]:
dataset

Age  Salary  Purchased Plot
0     22   22990               0
1     38   24200               0
2     29   52030               0
3     30   68970               0
4     22   91960               0
..   ...     ...             ...
395   49   49610               1
396   54   27830               1
397   53   24200               1
398   39   39930               0
399   52   43560               1

[400 rows x 3 columns]

In [4]:
#Step 3: Divide Feature Matrix(X) and Dependable Variable Vector(Y)
X=dataset.iloc[:,:-1].values  
Y=dataset.iloc[:,-1].values 

In [5]:
X

array([[    22,  22990],
       [    38,  24200],
       [    29,  52030],
       [    30,  68970],
       [    22,  91960],
       [    30,  70180],
       [    30, 101640],
       [    35, 181500],
       [    28,  39930],
       [    38,  78650],
       [    29,  96800],
       [    29,  62920],
       [    23, 104060],
       [    35,  21780],
       [    21,  99220],
       [    32,  96800],
       [    50,  30250],
       [    48,  31460],
       [    49,  33880],
       [    51,  35090],
       [    48,  26620],
       [    50,  59290],
       [    51,  49610],
       [    48,  26620],
       [    49,  27830],
       [    50,  24200],
       [    52,  33880],
       [    50,  36300],
       [    32,  52030],
       [    34,  21780],
       [    34,  89540],
       [    30, 165770],
       [    24,  19360],
       [    31,  53240],
       [    30, 108900],
       [    38,  32670],
       [    36,  33880],
       [    33,  59290],
       [    29,  87120],
       [    30,  37510],


In [6]:
#Step 4: Replace the missing data
from  sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,:]) 
X[:,:]=imputer.transform(X[:,:])


In [7]:
#Encoding isn't required
#Step 6 Splitting dataset into training and test data
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.2,random_state=1)

In [8]:
Xtrain

array([[    32,  33880],
       [    48,  26620],
       [    49, 141570],
       [    35,  21780],
       [    25,  98010],
       [    28, 105270],
       [    51,  39930],
       [    38,  70180],
       [    50,  27830],
       [    29,  38720],
       [    35, 163350],
       [    63,  41140],
       [    55,  25410],
       [    41,  66550],
       [    28, 108900],
       [    61,  45980],
       [    52, 106480],
       [    40,  94380],
       [    38,  93170],
       [    37,  52030],
       [    23,  59290],
       [    49, 106480],
       [    34,  41140],
       [    50,  36300],
       [    38,  60500],
       [    42, 116160],
       [    36, 136730],
       [    52, 104060],
       [    48,  95590],
       [    47,  47190],
       [    44,  71390],
       [    45,  64130],
       [    38,  88330],
       [    44,  87120],
       [    30, 116160],
       [    33, 140360],
       [    44,  62920],
       [    44,  62920],
       [    23,  99220],
       [    49,  49610],


In [9]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
Xtrain[:,:]=sc.fit_transform(Xtrain[:,:])
Xtest[:,:]=sc.fit_transform(Xtest[:,:])

# Build Classification Model

In [10]:
#Importing the Classification Model
from sklearn.linear_model import LogisticRegression
LoR=LogisticRegression(random_state=0)
LoR.fit(Xtrain,Ytrain)

LogisticRegression(random_state=0)

In [12]:
#Predicting the classification model
Yest=LoR.predict(Xtest)
np.concatenate((Yest.reshape(len(Yest),1),Ytest.reshape(len(Yest),1)),1)

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0,

# performance Matrix

In [13]:
#Confusion matrix
from sklearn.metrics import confusion_matrix
c=confusion_matrix(Ytest,Yest)
print(c)

[[43  5]
 [ 9 23]]


In [14]:
#Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(Ytest,Yest)

0.825

In [15]:
#precision
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score
c=confusion_matrix(Ytest,Yest)
print(c)
print(accuracy_score(Ytest,Yest))
print(precision_score(Ytest,Yest))

[[43  5]
 [ 9 23]]
0.825
0.8214285714285714
